// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiUm4yK2Pyvg8f-Jyq4l5po1OjjN45HVY',
    appId: '1:501772531313:web:0f1741ebc1c8c75e8bcdd0',
    messagingSenderId: '501772531313',
    projectId: 'aidea-11afa',
    authDomain: 'aidea-11afa.firebaseapp.com',
    storageBucket: 'aidea-11afa.firebasestorage.app',
    measurementId: 'G-XDLWB1G5DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW097hHs8kvzQ0V3p9LFgXjqb8d5dh3I',
    appId: '1:501772531313:android:257eca2a45eb86888bcdd0',
    messagingSenderId: '501772531313',
    projectId: 'aidea-11afa',
    storageBucket: 'aidea-11afa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1vQoCID-7hyOu8YWK-yEqlmyWl-_fwQ',
    appId: '1:501772531313:ios:02310b13e4cfc9278bcdd0',
    messagingSenderId: '501772531313',
    projectId: 'aidea-11afa',
    storageBucket: 'aidea-11afa.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1vQoCID-7hyOu8YWK-yEqlmyWl-_fwQ',
    appId: '1:501772531313:ios:02310b13e4cfc9278bcdd0',
    messagingSenderId: '501772531313',
    projectId: 'aidea-11afa',
    storageBucket: 'aidea-11afa.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiUm4yK2Pyvg8f-Jyq4l5po1OjjN45HVY',
    appId: '1:501772531313:web:675b1a1d810fefb08bcdd0',
    messagingSenderId: '501772531313',
    projectId: 'aidea-11afa',
    authDomain: 'aidea-11afa.firebaseapp.com',
    storageBucket: 'aidea-11afa.firebasestorage.app',
    measurementId: 'G-C57FY24HED',
  );
}
